apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-database
spec:
  selector:
    matchLabels:
      app: postgres-k8s-deployment
  serviceName: postgres-k8s-service
  replicas: 3
  template:
    metadata:
      labels:
        app: postgres-k8s-deployment
    spec:
      containers:
        - name: postgres-k8s-deployment
          image: postgres
          volumeMounts:
            - name: postgres-disk
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: ultradb
  volumeClaimTemplates:
    - metadata:
        name: postgres-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 0.01Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-k8s-service
  labels:
    name: postgres-k8s-deployment
spec:
  ports:
    - nodePort: 30172
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-k8s-deployment
  type: NodePort