apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-k8s-deployment
    spec:
      containers:
        - name: springboot-k8s-deployment
          image: ultra-service-springboot
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
  labels:
    name: springboot-k8s-deployment
spec:
  ports:
    - nodePort: 30171
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-k8s-deployment
  type: NodePort