{
 "title": "Ultra Service Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "content": "<img src=\"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2F10j1sRnpiklXB6%2Fgiphy.gif&f=1&nofb=1\"/>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 11, "x": 6, "y": 1 },
   "content": "<h1 style=\"font-size: 6em;\">Ultra Service Monitor</h1>\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "content": "\n<img src=\"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2F10j1sRnpiklXB6%2Fgiphy.gif&f=1&nofb=1\"/>"
  },
  { "title": "JVM + Sprinboot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "System load",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(system_load_average_1m)" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Http Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_max{method=\"GET\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(http_server_requests_seconds_max{method=\"POST\"})",
     "legendFormat": "Post"
    },
    {
     "expr": "sum(http_server_requests_seconds_max{method=\"PUT\"})",
     "legendFormat": "Put"
    },
    {
     "expr": "sum(http_server_requests_seconds_max{method=\"DELETE\"})",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage ", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total[5m])"
      }
     ]
    },
    {
     "title": "Average start time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(process_start_time_seconds)"
      }
     ]
    }
   ]
  }
 ]
}