name: Build and test Springboot
on: push
jobs:
  test_push_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v3
      - run: mvn package clean
    
