name: Build and test Springboot
on: push
jobs:
  test_push_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Build and Test	
        uses: qcastel/github-actions-maven/actions/maven@master
        with:
          maven-args: "clean install"
    
